### PR TITLE
Add Homebrew tap publication

### LINKED ISSUE #43: Consider setting up Homebrew distribution via a tap
The installation instructions could be simplified greatly if we use Homebrew for distribution. Per discussions, it would be good to set up a private tap and configure `goreleaser` to keep it up to date.

We need to ensure that MacOS distribution works without Gatekeeper problems; I don't think that signing/notarizing the binaries should be required for brew installs, but this needs verification.

### PR DESCRIPTION
**Pull request by rnorth**
Fixes #43

Will cause each released version to have a formula pushed to Skyscanner/homebrew-tools

### CODE REVIEW

**Comment by rnorth** [comment]
Note that I've not updated the docs deliberately - I want to see this properly creating the formula file first!

**Review by sledigabel — DISMISSED** [review]
LGTM, will create a simple brew tap and upload it to the skyscanner/homebrew-tools repo.

**Review by sledigabel — APPROVED** [review]
LGTM

**Comment by rnorth** [comment]
Thanks @sledigabel!

**Pull request merged**
