### PR TITLE
Add git clone command

### PR DESCRIPTION
**Pull request by Macavirus**
Partially addresses #48 

This makes no actual changes to any commands, but adds the ability to call `Clone` function.

As there is still some ambiguity around how we should address the actual `turbolift clone` command, I will address that in a followup PR.

@sledigabel @rnorth  would you prefer to preserve current behaviour in `clone.go` to fork by default? I think not forking by default is more user-friendly in general, but it sounds like the Skyscanner use case requires bulk forking. 

My suggestion would be to make the new Clone command default, and place `ForkAndClone` behind a different cobra command.

### CODE REVIEW

**Comment by sledigabel** [comment]
Your suggestion makes a lot of sense and I don't have any objection for this to be the default behaviour.
On the other hand I don't think `forkAndClone` should be a separate command, since it's partially the behaviour of `clone`.
Perhaps a simple flag such as `--fork` to make the behaviour explicitly forking?

**Comment by rnorth** [comment]
Argh I should have put [this comment](https://github.com/Skyscanner/turbolift/issues/48#issuecomment-841802867) here. But yes, I agree with @sledigabel!

**Review by rnorth — COMMENTED** [review]
I think this looks fine to me if we’re just implementing the ‘back half’ of the feature. I’d suggest, though, doing the modifications to the `clone` cobra command as well.

**Comment by sledigabel** [comment]
Agreed with @rnorth, let's add the whole thing into this PR rather than breaking it down into multiple PRs as we have agreed this will be the new default.

**Comment by sledigabel** [comment]
@Macavirus how do you want to proceed? do you want to amend this PR and change the default behaviour of `clone`? I'm happy to add on to your PR if you're swamped, this feature would be a great addition.

**Comment by rnorth** [comment]
@sledigabel shall we discuss one of us picking this up some time?

**Comment by sledigabel** [comment]
GMTA, I have a draft for this :-) publishing soon

**Comment by sledigabel** [comment]
Merging this and will iterate from there.

Thanks a lot for your contribution @Macavirus !

**Review by sledigabel — APPROVED** [review]

**Pull request merged**
