### PR TITLE
Disabling all arguments after foreach

### LINKED ISSUE #50: foreach sed fails with 'unknown shorthand flag' error
I get the following error when running foreach sed with turbolift 2:

`$ turbolift foreach sed -i '' 's/foo/bar/g' README.md 
                         
Error: unknown shorthand flag: 'i' in -i
Usage:
  turbolift foreach -- SHELL_COMMAND [flags]
Flags:
  -h, --help   help for foreach
Global Flags:
  -v, --verbose   verbose output
2021/05/21 11:49:08 unknown shorthand flag: 'i' in -i`

A temporary workaround is to encapsulate the sed command in double quotes, but I think this is a bug in the way parameters are handled. (also some of the README examples do not work either)

### PR DESCRIPTION
**Pull request by sledigabel**
Fixes #50.
Uses `DisableFlagParsing` as per the documentation to disable the
subsequent flag parsing in the command and leaving it as arguments to
the shell command.

Added `TraverseChildren` to rootCmd to allow -v and -h to be parsed.

https://pkg.go.dev/github.com/spf13/cobra#Command

Tested on Mac OS.

I'm unable to write tests as we're not testing the flag parsing at the
moment.

### CODE REVIEW

**Comment by sledigabel** [comment]
image

**Review by DiogoMCampos — APPROVED** [review]
LGTM! Nice that you got the `TraverseChildren` one in too! :+1:

**Review by rnorth — APPROVED** [review]

**Comment by sledigabel** [comment]
I'm gonna hold off the merge for now, I'd really to figure out how docker did it and make sure we can come back and implement flags for the `foreach` in the future without too much work.

**Comment by rnorth** [comment]
@sledigabel do you want to discuss this further?

**Comment by sledigabel** [comment]
About to merge this; we'll get particular arguments for `foreach` as a special case, outside of `cobra`.

**Pull request merged**
